# this file exists to run multiple container
# for docker-compose, refer https://docs.docker.com/compose/
# reference: https://manfredmlange.medium.com/creating-a-dev-container-for-typescript-and-vs-code-part-1-e653bb95c27f
version: '3.7' # syntax version

services:
  devcontainer: # match with devcontainer.json's service name
    image: louislim899899/react-profile-dev-container:0.1  # give image a tag after built
    build: .  # built context for docker compose, path is relative to docker-compose.yml location. Docker will look into this location for a file named DockerFile & use that file to build image
    container_name: react-profile-dev-container  # give container a readable name
    hostname: react-profile-dev.local  # give container a hostname, used for virtual connection between containers
    working_dir: /profile   # define working directory once the container started
    volumes:  # mount volume
       - ..:/profile  # refer to root or up a level before /src
       # Allow AWS CLI and other tools to read an AWS profile
       - ~/.aws:/home/node/.aws   # show you how you can make other file or directory available within your container
    command: sleep infinity # instruct docker which command to start when container is running. sleep infinity - container start and terminate immediately